# Generated by Django 4.1 on 2022-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooveapi', '0002_alter_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylineup',
            name='shows',
            field=models.ManyToManyField(related_name='lineups', to='grooveapi.show'),
        ),
    ]
