# Generated by Django 4.1 on 2022-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooveapi', '0003_mylineup_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grooveuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
    ]
